### PR TITLE
improve support for namespaced models

### PR DESCRIPTION
**Pull request by BM5k**
rebase changes from preston/railroady#65 and singlebrook/railroady#1

### CODE REVIEW

**Comment by BM5k** [comment]
I apologize for the lack of tests; my original changes were made months ago, and I’m not working on the project that I’d been using them for anymore.

Hopefully someone with more familiarity with the railroady codebase can comment on how useful these changes are.

**Comment by adarr** [comment]
Thanks for the improvement ! No more bug for me with thiese modifications. diagram:all and diagram:all_with_engines are working well and now take into consideration namespaces for controllers and models classes.

**Comment by preston** [comment]
Any community objections to merging this in? Seems like a great patch.

**Comment by Ch4s3** [comment]
+1

**Pull request merged**
