### PR TITLE
Patch aasm_diagram to support Rails 4 and AASM 4

### PR DESCRIPTION
**Pull request by Neson**
This works for me to generate the AASM diagram on my Rails 4.2.6 and AASM 4.10.1 project.

### CODE REVIEW

**Comment by preston** [comment]
Can anyone that uses AASM commit on this? I don't use this feature so it's hard for me to comment on what, if any, the implications are. :-/ I'm happy to merge if it isn't doesn't break support.

Has AASM support been broken and just went unreported?

**Comment by preston** [comment]
@Neson Is AASM support broken in the current release version?

**Comment by davidferril** [comment]
@preston yes it seems to be. 
running 
`railroady -A -s app/models/<some_model>.rb` 
yields
`.../gems/railroady-1.5.1/lib/railroady/aasm_diagram.rb:66:in `block in process_acts_as_state_machine_class': undefined method `initial_state' for <SomeModel>:Class (NoMethodError)`

when using it with Rails 4.2.5 and AASM 4.2.0

this patch seems to fix exactly that

**Comment by preston** [comment]
A'ight .. I'll make a note to merge this in to the next maintenance release. Holiday weekend here but I'll try to get to it soon!

**Comment by preston** [comment]
Merged in via cherry pick in commit 78d2a5ab4b989e95088760f8ef5d9058133c0ab3.

**Comment by preston** [comment]
@davidferril @Neson Released in v1.5.2!

**Pull request closed without merging**
